In [1]:
import torch
import torch.nn as nn

In [ ]:
# creating model class

class nnModel(nn.Module): # we have to inherent the nn.Module class in our class

  def __init__(self,num_features):
    super().__init__()              # invoking the parent class constructor
    self.linear = nn.Linear(num_features,1) # creating linear layer
    self.sigmoid = nn.Sigmoid() # activation function

# forward pass function
  def forward(self,X):
    X = self.linear(X)
    X = self.sigmoid(X)
    return X


In [ ]:
# creating data
data = torch.rand(10,5)
print(data)

tensor([[0.5535, 0.2436, 0.3970, 0.8280, 0.2811],
        [0.7667, 0.6435, 0.1088, 0.4492, 0.7695],
        [0.9690, 0.0559, 0.8971, 0.8003, 0.4075],
        [0.9781, 0.8475, 0.0896, 0.1353, 0.7658],
        [0.1423, 0.8387, 0.8663, 0.4162, 0.1066],
        [0.0937, 0.6195, 0.2834, 0.6710, 0.3329],
        [0.8524, 0.7509, 0.3122, 0.0919, 0.9024],
        [0.9809, 0.5556, 0.3283, 0.0394, 0.0267],
        [0.4275, 0.4652, 0.8372, 0.3162, 0.1152],
        [0.1663, 0.3107, 0.8231, 0.6724, 0.4380]])


In [ ]:
# creating model
model = nnModel(data.shape[1])

# calling forwardpass function
# model.forward(data)
# instead of above line you can also write as
model(data) # nn model have magic fucntion internally, who ensures that whenever object of class is called forward function get triggered

tensor([[0.3754],
        [0.4453],
        [0.4357],
        [0.4714],
        [0.2936],
        [0.3218],
        [0.4819],
        [0.4227],
        [0.3574],
        [0.3538]], grad_fn=<SigmoidBackward0>)

we got 10 outputs because we have 10 samples in our data

In [ ]:
# model weights
model.linear.weight

Parameter containing:
tensor([[ 0.3835, -0.3832, -0.0892, -0.3256,  0.4331]], requires_grad=True)

In [ ]:
# model bias
model.linear.bias

Parameter containing:
tensor([-0.4446], requires_grad=True)

In [ ]:
# summarising this model architecture

!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
nnModel                                  [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# =================================================

**Creating Neural Network having one hidden layer with 3 neurons and one output layer with one neuron**

In [ ]:
class dnn(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,X):
    X = self.linear1(X)
    X = self.relu(X)
    X = self.linear2(X)
    X = self.sigmoid(X)

    return X

In [ ]:
data

tensor([[0.5535, 0.2436, 0.3970, 0.8280, 0.2811],
        [0.7667, 0.6435, 0.1088, 0.4492, 0.7695],
        [0.9690, 0.0559, 0.8971, 0.8003, 0.4075],
        [0.9781, 0.8475, 0.0896, 0.1353, 0.7658],
        [0.1423, 0.8387, 0.8663, 0.4162, 0.1066],
        [0.0937, 0.6195, 0.2834, 0.6710, 0.3329],
        [0.8524, 0.7509, 0.3122, 0.0919, 0.9024],
        [0.9809, 0.5556, 0.3283, 0.0394, 0.0267],
        [0.4275, 0.4652, 0.8372, 0.3162, 0.1152],
        [0.1663, 0.3107, 0.8231, 0.6724, 0.4380]])

In [ ]:
dnn_model = dnn(data.shape[1])

In [ ]:
dnn_model

dnn(
  (linear1): Linear(in_features=5, out_features=3, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [ ]:
# forward pass
dnn_model(data)

tensor([[0.3990],
        [0.3854],
        [0.4484],
        [0.3947],
        [0.4186],
        [0.3733],
        [0.4015],
        [0.4275],
        [0.4266],
        [0.4087]], grad_fn=<SigmoidBackward0>)

In [ ]:
dnn_model.linear1.weight

Parameter containing:
tensor([[ 0.0022,  0.3069,  0.3586,  0.1364,  0.2847],
        [ 0.3431,  0.0980,  0.2052,  0.1473, -0.4365],
        [-0.1860,  0.3834, -0.1588,  0.3031,  0.0765]], requires_grad=True)

In [ ]:
dnn_model.linear1.bias

Parameter containing:
tensor([-0.3899,  0.3001,  0.1568], requires_grad=True)

In [ ]:
dnn_model.linear2.weight

Parameter containing:
tensor([[ 0.4243,  0.3412, -0.3518]], requires_grad=True)

In [ ]:
dnn_model.linear2.bias

Parameter containing:
tensor([-0.4963], requires_grad=True)

In [ ]:
summary(dnn_model)

Layer (type:depth-idx)                   Param #
dnn                                      --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

**Using Sequential Containers**

In [ ]:
class dnn1(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid(),
    )

  def forward(self,X):
    out =  self.network(X)
    return out

In [ ]:
data

tensor([[0.5535, 0.2436, 0.3970, 0.8280, 0.2811],
        [0.7667, 0.6435, 0.1088, 0.4492, 0.7695],
        [0.9690, 0.0559, 0.8971, 0.8003, 0.4075],
        [0.9781, 0.8475, 0.0896, 0.1353, 0.7658],
        [0.1423, 0.8387, 0.8663, 0.4162, 0.1066],
        [0.0937, 0.6195, 0.2834, 0.6710, 0.3329],
        [0.8524, 0.7509, 0.3122, 0.0919, 0.9024],
        [0.9809, 0.5556, 0.3283, 0.0394, 0.0267],
        [0.4275, 0.4652, 0.8372, 0.3162, 0.1152],
        [0.1663, 0.3107, 0.8231, 0.6724, 0.4380]])

In [ ]:
dnn_model1 = dnn1(data.shape[1])

dnn_model1(data)

tensor([[0.4429],
        [0.4578],
        [0.4595],
        [0.4602],
        [0.4438],
        [0.4450],
        [0.4648],
        [0.4413],
        [0.4422],
        [0.4414]], grad_fn=<SigmoidBackward0>)

In [ ]:
dnn_model1.network

Sequential(
  (0): Linear(in_features=5, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
  (3): Sigmoid()
)

In [ ]:
dnn_model1.network[0].weight

Parameter containing:
tensor([[ 0.0214,  0.1727, -0.3264, -0.0177, -0.3887],
        [ 0.3531, -0.2703,  0.1111, -0.0973,  0.2147],
        [-0.1177,  0.2078, -0.2656, -0.1003,  0.0105]], requires_grad=True)

In [ ]:
dnn_model1.network[0].bias

Parameter containing:
tensor([ 0.2486, -0.1092,  0.2624], requires_grad=True)

In [ ]:
dnn_model1.network[2].weight

Parameter containing:
tensor([[-0.2491,  0.2410,  0.2119]], requires_grad=True)

In [ ]:
dnn_model1.network[2].bias

Parameter containing:
tensor([-0.2410], requires_grad=True)

# Implementing On Real Dataset

In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
# removing unnecessary columns
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [5]:
# train test split
X = df.drop('diagnosis', axis=1)
y = df['diagnosis']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [6]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(455, 30)
(114, 30)
(455,)
(114,)


In [7]:
# Scalling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
# scaling factors
print("Means:", scaler.mean_)  # Mean of each column
print("Standard Deviations:", scaler.scale_)

Means: [1.41242879e+01 1.93075604e+01 9.19396703e+01 6.56671429e+02
 9.63678681e-02 1.04421538e-01 8.91330895e-02 4.88284242e-02
 1.81880440e-01 6.29729011e-02 4.01258022e-01 1.21594813e+00
 2.82998967e+00 4.02369121e+01 6.97023297e-03 2.53466484e-02
 3.20967684e-02 1.16982505e-02 2.03582593e-02 3.78691055e-03
 1.62633495e+01 2.57886154e+01 1.07198791e+02 8.83610110e+02
 1.32334022e-01 2.55078505e-01 2.73968246e-01 1.15016442e-01
 2.91142857e-01 8.44703736e-02]
Standard Deviations: [3.62225359e+00 4.27993499e+00 2.48947679e+01 3.63480250e+02
 1.41342510e-02 5.22528208e-02 8.03982305e-02 3.88980010e-02
 2.76230170e-02 7.20564635e-03 2.85064897e-01 5.48878225e-01
 2.05144684e+00 4.81209261e+01 2.91838330e-03 1.77698849e-02
 3.15201184e-02 5.99222487e-03 8.33049058e-03 2.60496267e-03
 4.95037665e+00 6.15500551e+00 3.42256559e+01 5.87464840e+02
 2.23921729e-02 1.54854811e-01 2.10139639e-01 6.57771234e-02
 6.29427445e-02 1.82444544e-02]


In [9]:
# converting labels into numbers using Label encoding
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [10]:
# converting numpy arrays into pytorch tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [11]:
(X_train_tensor[0]).dtype

torch.float64

**Training Process**

In [40]:
class mydnn(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,X):
    X = self.linear(X)
    X = self.sigmoid(X)
    return X

  def lossFun(self, y_pred, y_true):
    # loss = nn.BCELoss()(y_pred, y_true) , we can write like this
    bceloss = nn.BCELoss()
    loss = bceloss(y_pred, y_true)
    return loss


In [41]:
# defining parameters
learning_rate = 0.1
epochs = 30

# creating Model
model = mydnn(X_train_tensor.shape[1])

# defining optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# training loop
for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor.float())

  # calculating loss
  loss = model.lossFun(y_pred,y_train_tensor.reshape(-1,1).float())

  # backward pass
  loss.backward()

  # updating weights and bais
  optimizer.step()

  # making gradient zero
  optimizer.zero_grad()

  # printing loss for each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.6737694144248962
Epoch: 2, Loss: 0.5422763228416443
Epoch: 3, Loss: 0.46575891971588135
Epoch: 4, Loss: 0.4148052930831909
Epoch: 5, Loss: 0.37770190834999084
Epoch: 6, Loss: 0.3491092622280121
Epoch: 7, Loss: 0.3262033462524414
Epoch: 8, Loss: 0.3073263168334961
Epoch: 9, Loss: 0.29142969846725464
Epoch: 10, Loss: 0.27781206369400024
Epoch: 11, Loss: 0.2659837603569031
Epoch: 12, Loss: 0.25559085607528687
Epoch: 13, Loss: 0.24637027084827423
Epoch: 14, Loss: 0.23812200129032135
Epoch: 15, Loss: 0.23069070279598236
Epoch: 16, Loss: 0.22395385801792145
Epoch: 17, Loss: 0.21781326830387115
Epoch: 18, Loss: 0.2121891975402832
Epoch: 19, Loss: 0.2070162296295166
Epoch: 20, Loss: 0.2022399753332138
Epoch: 21, Loss: 0.19781485199928284
Epoch: 22, Loss: 0.1937023401260376
Epoch: 23, Loss: 0.18986956775188446
Epoch: 24, Loss: 0.18628822267055511
Epoch: 25, Loss: 0.18293388187885284
Epoch: 26, Loss: 0.17978525161743164
Epoch: 27, Loss: 0.17682361602783203
Epoch: 28, Loss: 0.17

In [42]:
model.linear.weight

Parameter containing:
tensor([[ 0.1042,  0.1055,  0.2894,  0.3424, -0.0013,  0.1103,  0.1101,  0.2981,
          0.1329, -0.0713,  0.3168,  0.1365,  0.0573,  0.0186, -0.1701,  0.0339,
          0.0558, -0.0864,  0.0781,  0.0107,  0.4608,  0.1743,  0.3928,  0.2952,
          0.2334,  0.2130,  0.1547,  0.3122,  0.0478,  0.1059]],
       requires_grad=True)

In [43]:
model.linear.bias

Parameter containing:
tensor([-0.1633], requires_grad=True)

In [44]:
# model evaluation

with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float())
  y_pred = (y_pred > 0.7).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.5507848858833313
