# Load Dataset

# Basic Preprocessing

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
# removing unnecessary columns
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [ ]:
# train test split
X = df.drop('diagnosis', axis=1)
y = df['diagnosis']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(455, 30)
(114, 30)
(455,)
(114,)


In [ ]:
# Scalling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# scaling factors
print("Means:", scaler.mean_)  # Mean of each column
print("Standard Deviations:", scaler.scale_)

Means: [1.41242879e+01 1.93075604e+01 9.19396703e+01 6.56671429e+02
 9.63678681e-02 1.04421538e-01 8.91330895e-02 4.88284242e-02
 1.81880440e-01 6.29729011e-02 4.01258022e-01 1.21594813e+00
 2.82998967e+00 4.02369121e+01 6.97023297e-03 2.53466484e-02
 3.20967684e-02 1.16982505e-02 2.03582593e-02 3.78691055e-03
 1.62633495e+01 2.57886154e+01 1.07198791e+02 8.83610110e+02
 1.32334022e-01 2.55078505e-01 2.73968246e-01 1.15016442e-01
 2.91142857e-01 8.44703736e-02]
Standard Deviations: [3.62225359e+00 4.27993499e+00 2.48947679e+01 3.63480250e+02
 1.41342510e-02 5.22528208e-02 8.03982305e-02 3.88980010e-02
 2.76230170e-02 7.20564635e-03 2.85064897e-01 5.48878225e-01
 2.05144684e+00 4.81209261e+01 2.91838330e-03 1.77698849e-02
 3.15201184e-02 5.99222487e-03 8.33049058e-03 2.60496267e-03
 4.95037665e+00 6.15500551e+00 3.42256559e+01 5.87464840e+02
 2.23921729e-02 1.54854811e-01 2.10139639e-01 6.57771234e-02
 6.29427445e-02 1.82444544e-02]


In [ ]:
X_train

array([[ 0.02090193,  0.28562106,  0.01889271, ...,  0.28708398,
        -0.59963793, -0.32285831],
       [-0.53400124, -1.40599342, -0.51656117, ..., -0.50392051,
         0.88583908,  0.43518026],
       [-0.2551693 , -0.43868901, -0.3137073 , ..., -0.99299632,
        -0.22946024, -0.68461207],
       ...,
       [ 0.53715513,  0.08001046,  0.48846929, ...,  0.56225563,
        -0.41534346, -1.1291307 ],
       [ 1.28254744,  0.49590463,  1.24364806, ...,  1.36496632,
         1.21947563,  0.77994255],
       [-0.11437297, -0.1466285 , -0.12892951, ...,  0.20346828,
        -0.09918311,  0.32007679]])

In [ ]:
X_test

array([[-0.48706913, -0.17933928, -0.519373  , ..., -0.46515324,
         0.11370878, -0.69173752],
       [-0.02326947, -0.7774792 , -0.08675198, ..., -0.61550946,
        -0.29618755, -0.66488004],
       [-0.33522996, -0.69570226, -0.37797783, ..., -0.49662314,
         0.17884735, -0.82109189],
       ...,
       [-0.78522606, -1.38262858, -0.76078919, ..., -0.43946041,
        -1.28597597, -0.91153034],
       [ 0.20586965,  0.21085357,  0.16792001, ..., -0.20244792,
        -0.86178093, -1.01293101],
       [ 1.13070827, -0.1022353 ,  1.07493791, ...,  0.95144869,
        -0.15796669, -0.13650031]])

In [ ]:
y_train

476    B
130    B
246    B
205    M
16     M
      ..
552    B
393    M
75     M
337    M
523    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
y_test

107    B
437    B
195    B
141    M
319    B
      ..
19     B
313    B
139    B
495    B
317    M
Name: diagnosis, Length: 114, dtype: object

In [ ]:
# converting labels into numbers using Label encoding
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,

In [ ]:
y_test

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1])

In [ ]:
# converting numpy arrays into pytorch tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
print(X_train_tensor)
print(X_train_tensor.shape)

tensor([[ 0.0209,  0.2856,  0.0189,  ...,  0.2871, -0.5996, -0.3229],
        [-0.5340, -1.4060, -0.5166,  ..., -0.5039,  0.8858,  0.4352],
        [-0.2552, -0.4387, -0.3137,  ..., -0.9930, -0.2295, -0.6846],
        ...,
        [ 0.5372,  0.0800,  0.4885,  ...,  0.5623, -0.4153, -1.1291],
        [ 1.2825,  0.4959,  1.2436,  ...,  1.3650,  1.2195,  0.7799],
        [-0.1144, -0.1466, -0.1289,  ...,  0.2035, -0.0992,  0.3201]],
       dtype=torch.float64)
torch.Size([455, 30])


In [ ]:
print(y_train_tensor)
print(y_train_tensor.shape)

tensor([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
        0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,

In [ ]:
X.shape

(569, 30)

# Training Process

In [ ]:
# Defining model

class MyNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forwardPass(self,x_train):
    z = torch.matmul(x_train,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def lossFunction(self,y_true,y_pred):
    # clamp predictions to avoid log(0)
    EPS = 1e-15
    y_pred_clipped = y_pred.clamp(min=EPS, max=1-EPS)
    loss = -torch.mean(y_true * torch.log(y_pred_clipped) + (1 - y_true) * torch.log(1 - y_pred_clipped))
    return loss

In [ ]:
# defining parameters
learning_rate = 0.1
epochs = 30

# creating Model
model = MyNN(X_train_tensor)

# training loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forwardPass(X_train_tensor)

  # calculating loss
  loss = model.lossFunction(y_train_tensor,y_pred)

  # backward pass
  loss.backward()

  # updating weights and bais
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # making gradient zero
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # printing loss for each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.7670660076426
Epoch: 2, Loss: 3.5635235725818855
Epoch: 3, Loss: 3.3605377033258144
Epoch: 4, Loss: 3.153241107151515
Epoch: 5, Loss: 2.9473342400572102
Epoch: 6, Loss: 2.7432574241778496
Epoch: 7, Loss: 2.5414554358549966
Epoch: 8, Loss: 2.3425291662778123
Epoch: 9, Loss: 2.1472689924207096
Epoch: 10, Loss: 1.9567155607658984
Epoch: 11, Loss: 1.7722323956645816
Epoch: 12, Loss: 1.5955833004272786
Epoch: 13, Loss: 1.4289953063514373
Epoch: 14, Loss: 1.2751673084641306
Epoch: 15, Loss: 1.137156662538843
Epoch: 16, Loss: 1.0180542281410512
Epoch: 17, Loss: 0.9203841165175676
Epoch: 18, Loss: 0.8452933075074036
Epoch: 19, Loss: 0.7918141419732526
Epoch: 20, Loss: 0.7566840125343601
Epoch: 21, Loss: 0.7351431638588164
Epoch: 22, Loss: 0.7224070838279062
Epoch: 23, Loss: 0.7147950892718586
Epoch: 24, Loss: 0.7099710544269409
Epoch: 25, Loss: 0.7066241976130753
Epoch: 26, Loss: 0.7040673736212605
Epoch: 27, Loss: 0.7019512794740549
Epoch: 28, Loss: 0.7000997019764779
Epoch:

In [ ]:
model.weights

tensor([[-0.0194],
        [ 0.1857],
        [-0.0522],
        [ 0.2963],
        [ 0.1516],
        [-0.2161],
        [-0.4828],
        [-0.3331],
        [ 0.0901],
        [-0.0019],
        [ 0.3039],
        [ 0.0224],
        [-0.0324],
        [-0.2037],
        [ 0.0066],
        [ 0.2314],
        [ 0.3606],
        [-0.0650],
        [ 0.0199],
        [-0.2332],
        [ 0.3516],
        [-0.0775],
        [-0.1567],
        [ 0.1294],
        [-0.0669],
        [-0.0189],
        [-0.2614],
        [ 0.1031],
        [ 0.2665],
        [ 0.3161]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.1982], dtype=torch.float64, requires_grad=True)

# Model Evaluation

In [ ]:
with torch.no_grad():
  y_pred = model.forwardPass(X_test_tensor)
  y_pred = (y_pred > 0.7).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.6292705535888672
