In [3]:
import torch

In [4]:
print(torch.__version__)

2.5.1+cu121


In [ ]:
if torch.cuda.is_available():
    print("cuda is available")
    print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("cuda is not available")

cuda is not available


## Creating Tensor

In [ ]:
# using empty -> functions allocates memmory you mention, and gives values which are already available on that memory
a = torch.empty(4,2,3)
print(a)

tensor([[[-7.0571e-05,  3.1866e-41, -7.0569e-05],
         [ 3.1866e-41,  2.3822e-44,  0.0000e+00]],

        [[-1.6527e-08,  3.1866e-41, -7.0571e-05],
         [ 3.1866e-41,  0.0000e+00,  0.0000e+00]],

        [[ 4.2039e-45,  8.4078e-45,  4.2039e-45],
         [ 9.8091e-45,  1.6241e-42,  4.4637e-41]],

        [[-7.0572e-05,  3.1866e-41,  2.2421e-44],
         [ 3.3631e-44, -7.0571e-05,  3.1866e-41]]])


In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
b = torch.zeros(2,4)
print(b)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
# using ones
c = torch.ones(2,4)
print(c)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
# using rand

"""torch.rand() generates values uniformly distributed between 0 and 1
(inclusive of 0 but exclusive of 1). This means all the random values it produces
will lie in the range [0, 1)."""

d = torch.rand(2,3)
print(d)

tensor([[0.8342, 0.6152, 0.1734],
        [0.0600, 0.1897, 0.6493]])


If you want random numbers in a different range, you can scale and shift the values. For example:

To generate numbers in the range [a, b]:
result
=
𝑎
+
(
𝑏
−
𝑎
)
×
torch.rand()

In [ ]:
# Generate a 2x3 tensor with random values in the range [10, 20)
a, b = 10, 20
random_tensor_scaled = a + (b - a) * torch.rand(2, 3)
print(random_tensor_scaled)

tensor([[13.0228, 10.9065, 10.5161],
        [17.6037, 16.0777, 12.2646]])


In [ ]:
t1 = torch.rand(2,3)
t2 = a + (b-a) * torch.rand(2,3)

print("t1 : \n", t1)
print("\n\nt2 : \n", t2)

t1 : 
 tensor([[0.4910, 0.1540, 0.7716],
        [0.4840, 0.8972, 0.5602]])


t2 : 
 tensor([[13.5817, 17.7103, 17.4324],
        [18.5232, 10.9784, 11.5947]])


In [ ]:
# manual_seed -> if we want to reproduce same random numbers each time we use seed
torch.manual_seed(42)
e = torch.rand(2,3)
print(e)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [ ]:
torch.manual_seed(42)
f = torch.rand(2,3)
print(f)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [ ]:
# using tensor
g = torch.tensor([[1,2,3],[4,5,6]])
print(g)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
h = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(h)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])


In [ ]:
print(h.shape)
print(type(h))
print(h.ndim)
print(h.size())

torch.Size([3, 2, 2])
<class 'torch.Tensor'>
3
torch.Size([3, 2, 2])


In [ ]:
# other ways of creating tensor

# arange
print("using arange => ", torch.arange(3,15,3))

# using linspace
print("using line => ",torch.linspace(1,10,20))

# using eye -> identity matrix
print("using eye => ", torch.eye(5))

# using full -> prints desire shapes tensor with desire number in all places
print("using full => ", torch.full((2,3),4))

using arange =>  tensor([ 3,  6,  9, 12])
using line =>  tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])
using eye =>  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full =>  tensor([[4, 4, 4],
        [4, 4, 4]])


In [ ]:
# generating tensor with same shape like other priviously made tensor

print(torch.zeros_like(g))
print(torch.ones_like(g))
print(torch.empty_like(g))

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[136816132202160, 136816132202160, 136811888246784],
        [            449, 136816132202128, 136816132202128]])


In [ ]:
# will get error because tensor g have int values and rand function generate float values
print(torch.rand_like(g))

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
print(torch.rand_like(g, dtype=torch.float32))

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


## Tensor DataTypes

In [ ]:
print(c)
print(c.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


In [ ]:
print(g)
print(g.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64


In [ ]:
# creating tensor with desire dtye
h = torch.tensor([1,2,3], dtype=torch.float32)
print(h)
print(h.dtype)

tensor([1., 2., 3.])
torch.float32


In [ ]:
# converting the dtype of already available tensor
h.to(dtype=torch.int64)

tensor([1, 2, 3])

# Tensor operations on CPU

## Mathematical operations

### 1. Scalar operations

In [ ]:
x = torch.rand(2,3)
print(x)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


In [ ]:
# addition
print(2 + x)

# substraction
print(x - 1)

# multiplication
print(x*6)

# division
print(x/2)

# int division
print((x*100) // 3)

# mod
print((x*100) % 2)

# power
print(x**2)


tensor([[1.7388, 1.1354, 1.4822],
        [0.8588, 1.7709, 1.1478]])
tensor([[-0.1306, -0.4323, -0.2589],
        [-0.5706, -0.1146, -0.4261]])
tensor([[5.2164, 3.4063, 4.4466],
        [2.5764, 5.3127, 3.4434]])
tensor([[0.4347, 0.2839, 0.3705],
        [0.2147, 0.4427, 0.2870]])
tensor([[28., 18., 24.],
        [14., 29., 19.]])
tensor([[0.9404, 0.7715, 0.1094],
        [0.9404, 0.5443, 1.3904]])
tensor([[0.7559, 0.3223, 0.5492],
        [0.1844, 0.7840, 0.3294]])


### 2. Element wise operations

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(f"a : {a}")
print(f"b : {b}")

a : tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])
b : tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])


In [ ]:
# add
print(a + b)
print(torch.add(a,b))

tensor([[0.3719, 0.8969, 0.6284],
        [0.6407, 0.8441, 0.8378]])
tensor([[0.3719, 0.8969, 0.6284],
        [0.6407, 0.8441, 0.8378]])


In [ ]:
# substraction
print(a - b)
print(torch.sub(a,b))

tensor([[ 0.1613,  0.3580, -0.0892],
        [ 0.2420, -0.2503,  0.8255]])
tensor([[ 0.1613,  0.3580, -0.0892],
        [ 0.2420, -0.2503,  0.8255]])


In [ ]:
# multiplication
print(a * b)
print(torch.mul(a,b))

tensor([[0.0281, 0.1691, 0.0967],
        [0.0880, 0.1625, 0.0051]])
tensor([[0.0281, 0.1691, 0.0967],
        [0.0880, 0.1625, 0.0051]])


In [ ]:
# division
print(a / b)
print(torch.div(a,b))

tensor([[  2.5313,   2.3282,   0.7515],
        [  2.2139,   0.5426, 135.0043]])
tensor([[  2.5313,   2.3282,   0.7515],
        [  2.2139,   0.5426, 135.0043]])


In [ ]:
# power
print(a ** b)
print(torch.pow(a,b))

tensor([[0.8700, 0.8820, 0.6248],
        [0.8495, 0.5146, 0.9989]])
tensor([[0.8700, 0.8820, 0.6248],
        [0.8495, 0.5146, 0.9989]])


In [ ]:
# mod
print(a % b)
print(torch.remainder(a,b))

tensor([[5.5950e-02, 8.8459e-02, 2.6963e-01],
        [4.2636e-02, 2.9692e-01, 2.6345e-05]])
tensor([[5.5950e-02, 8.8459e-02, 2.6963e-01],
        [4.2636e-02, 2.9692e-01, 2.6345e-05]])


In [ ]:
# floor division
print(a // b)
print(torch.floor_divide(a,b))

tensor([[  2.,   2.,   0.],
        [  2.,   0., 135.]])
tensor([[  2.,   2.,   0.],
        [  2.,   0., 135.]])


In [ ]:
# absolute value
print(torch.abs(a-b))

tensor([[0.1613, 0.3580, 0.0892],
        [0.2420, 0.2503, 0.8255]])


In [ ]:
# negative
print(torch.neg(a-b))

tensor([[-0.1613, -0.3580,  0.0892],
        [-0.2420,  0.2503, -0.8255]])


In [ ]:
# round
print(torch.round(a))

tensor([[0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
# ceil
print(torch.ceil(a))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# floor
print(torch.floor(a))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
h = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(h)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])


In [ ]:
# clamp -> convert less than min value in value, and greater than max value max value
print(torch.clamp(h,5,10))

tensor([[[ 5,  5],
         [ 5,  5]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [10, 10]]])


### 3. Reduction Operations
**reducing tenson in single number**

In [ ]:
j = torch.tensor([[1,2,3],[4,5,6]])
print(j)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
h

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [ ]:
# sum
print(torch.sum(h))

# sum along layers
print(torch.sum(h, dim=0))

# sum along columns
print(torch.sum(h, dim=1))

# sum along rows
print(torch.sum(h, dim=2))

tensor(78)
tensor([[15, 18],
        [21, 24]])
tensor([[ 4,  6],
        [12, 14],
        [20, 22]])
tensor([[ 3,  7],
        [11, 15],
        [19, 23]])


In [ ]:
# sum along columns
print(torch.sum(j, dim=0))

# sum along rows
print(torch.sum(j, dim=1))

tensor([5, 7, 9])
tensor([ 6, 15])


In [ ]:
# mean
print(torch.mean(h))

# mean along layers
print(torch.mean(h, dim=0))

# mean along columns
print(torch.mean(h, dim=1))

# mean along rows
print(torch.mean(h, dim=2))

# to calculate mean you need flowt dtype and our tensor dtype is int

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
k = torch.rand(2,3,dtype=torch.float32)
print(k)

tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])


In [ ]:
# mean
print(torch.mean(k))

# mean along columns
print(torch.mean(k, dim=0))

# mean along rows
print(torch.mean(k, dim=1))

tensor(0.6071)
tensor([0.7674, 0.2065, 0.8475])
tensor([0.6376, 0.5766])


In [ ]:
# median
print(torch.median(k))

# max
print(torch.max(k))

# min
print(torch.min(k))

# argmax -> Finds the index of the largest value in a tensor.
print(torch.argmax(k))

# argmin -> Finds the index of the smallest value in a tensor.
print(torch.argmin(k))

tensor(0.5832)
tensor(0.9516)
tensor(0.0753)
tensor(0)
tensor(1)


In [ ]:
k

tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])

In [ ]:
# product
print(torch.prod(k))

# standard deviation
print(torch.std(k))

# variance
print(torch.var(k))

tensor(0.0101)
tensor(0.3444)
tensor(0.1186)


### 4. Metrix Operations

In [ ]:
l = torch.randint(size=(2,3), low=0, high=10)
m = torch.randint(size=(3,2), low=0, high=10)

print(l)
print(m)

tensor([[9, 6, 2],
        [0, 6, 2]])
tensor([[7, 9],
        [7, 3],
        [3, 4]])


In [ ]:
# matrix multiplication
print(torch.matmul(l,m))

tensor([[111, 107],
        [ 48,  26]])


In [ ]:
torch.randint(size=(3,), low=0, high=10)

tensor([0, 0, 1])

In [ ]:
# dotproduct -> It only works on 1D tensors.
n = torch.randint(size=(3,), low=0, high=10) # creating 1d tensors
o = torch.randint(size=(3,), low=0, high=10)

print(n)
print(o)

print(torch.dot(n,o))

tensor([2, 0, 9])
tensor([8, 5, 3])
tensor(43)


In [ ]:
# transpose
print(l)
print(l.T)

tensor([[9, 6, 2],
        [0, 6, 2]])
tensor([[9, 0],
        [6, 6],
        [2, 2]])


In [ ]:
torch.transpose(l,0,1)

tensor([[9, 0],
        [6, 6],
        [2, 2]])

In [ ]:
print(h)
print("\n------\n")
print(torch.transpose(h,1,2))
print("\n------\n")
print(torch.transpose(h,0,1))
print("\n------\n")
print(torch.transpose(h,0,2))

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

------

tensor([[[ 1,  3],
         [ 2,  4]],

        [[ 5,  7],
         [ 6,  8]],

        [[ 9, 11],
         [10, 12]]])

------

tensor([[[ 1,  2],
         [ 5,  6],
         [ 9, 10]],

        [[ 3,  4],
         [ 7,  8],
         [11, 12]]])

------

tensor([[[ 1,  5,  9],
         [ 3,  7, 11]],

        [[ 2,  6, 10],
         [ 4,  8, 12]]])


In [ ]:
# determinant -> needs float values to calculate det
p = torch.randint(size=(2,2), low=0, high=10,dtype=torch.float32)
print(p)

print(torch.det(p))

tensor([[7., 5.],
        [8., 5.]])
tensor(-5.0000)


In [ ]:
# innverse
print(torch.inverse(p))

tensor([[-1.0000,  1.0000],
        [ 1.6000, -1.4000]])


In [ ]:
q = torch.randint(size=(3,3), low=0, high=10,dtype=torch.float32)
print(q,"\n=========\n")

print(torch.det(q),"\n=======\n")
print(torch.inverse(q))

tensor([[4., 1., 1.],
        [0., 9., 0.],
        [9., 1., 8.]]) 

tensor(207.) 

tensor([[ 0.3478, -0.0338, -0.0435],
        [ 0.0000,  0.1111,  0.0000],
        [-0.3913,  0.0242,  0.1739]])


### 5. Comparison Operations

In [ ]:
r = torch.randint(size=(2,3), low=10, high=20,dtype=torch.float32)
s = torch.randint(size=(2,3), low=30, high=50)

print(r)
print(s)

tensor([[16., 10., 16.],
        [18., 16., 18.]])
tensor([[40, 46, 49],
        [30, 45, 49]])


In [ ]:
# greater than
print(r > s)

# less than
print(r < s)

# equal to
print(r == s)

# greater than or equal to
print(r >= s)

# less than or equal to
print(r <= s)

tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


### 6. Special functions

In [ ]:
# log
print(torch.log(r))

# exp
print(torch.exp(r))

# sin
print(torch.sin(r))

# cos
print(torch.cos(r))

# tan
print(torch.tan(r))

tensor([[2.7726, 2.3026, 2.7726],
        [2.8904, 2.7726, 2.8904]])
tensor([[8.8861e+06, 2.2026e+04, 8.8861e+06],
        [6.5660e+07, 8.8861e+06, 6.5660e+07]])
tensor([[-0.2879, -0.5440, -0.2879],
        [-0.7510, -0.2879, -0.7510]])
tensor([[-0.9577, -0.8391, -0.9577],
        [ 0.6603, -0.9577,  0.6603]])
tensor([[ 0.3006,  0.6484,  0.3006],
        [-1.1373,  0.3006, -1.1373]])


In [ ]:
# square root
print(torch.sqrt(r))

# square
print(torch.square(r))

# sigmoid
print(torch.sigmoid(r))

# softmax
print(torch.softmax(r,dim=1))

# tanh
print(torch.tanh(r))

tensor([[4.0000, 3.1623, 4.0000],
        [4.2426, 4.0000, 4.2426]])
tensor([[256., 100., 256.],
        [324., 256., 324.]])
tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])
tensor([[0.4994, 0.0012, 0.4994],
        [0.4683, 0.0634, 0.4683]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
r

tensor([[16., 10., 16.],
        [18., 16., 18.]])

### 6. Inplace Operations

to use inplace operation you just need to add "_" infront of any function.

In [ ]:
a = torch.tensor([[1,2,3],[5,7,8]])

In [ ]:
id(a)

139048921691488

In [ ]:
id(a.add_(b))

139048921691488

In [ ]:
id(torch.add(a,b))

139048934782784

In [ ]:
a.to(torch.float32).sigmoid_()

tensor([[0.8808, 0.9820, 0.9975],
        [1.0000, 1.0000, 1.0000]])

In [ ]:
a.mul_(b) # we are storing multiplication results in location of a

tensor([[   4,   16,   36],
        [3600,  196,  256]])

## Copying a Tensor

In [ ]:
a

tensor([[   5,   18,   39],
        [3605,  203,  264]])

In [ ]:
b = a # we are assigning new var b to a, not creating copy

In [ ]:
b

tensor([[   5,   18,   39],
        [3605,  203,  264]])

In [ ]:
a[1][0] = 30

In [ ]:
a

tensor([[  5,  18,  39],
        [ 30, 203, 264]])

In [ ]:
b

tensor([[  5,  18,  39],
        [ 30, 203, 264]])

In [ ]:
id(a) == id(b)

True

In [ ]:
c = a.clone() # we are creating copy of a

In [ ]:
c

tensor([[  5,  18,  39],
        [ 30, 203, 264]])

In [ ]:
id(a) == id(c)

False

In [ ]:
a[0][0] = 0
print(a)

tensor([[  0,  18,  39],
        [ 30, 203, 264]])


In [ ]:
print(c)

tensor([[  5,  18,  39],
        [ 30, 203, 264]])


# Tensor Operations on GPU

In [4]:
torch.cuda.is_available()

True

In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [6]:
device

device(type='cuda')

### Creating tensors on GPU

In [7]:
# creating new tensors
tn1 = torch.rand((3,2),device=device)
tn2 = torch.rand((3,2,4),device=device)

In [9]:
print(tn1)
print("\n",tn2)

tensor([[0.3908, 0.0410],
        [0.4119, 0.4350],
        [0.5944, 0.2180]], device='cuda:0')

 tensor([[[0.5838, 0.1093, 0.6190, 0.6114],
         [0.0443, 0.1172, 0.3722, 0.2988]],

        [[0.3600, 0.2274, 0.5736, 0.9365],
         [0.4428, 0.8404, 0.8372, 0.9751]],

        [[0.7128, 0.4325, 0.3115, 0.5512],
         [0.9914, 0.1480, 0.9058, 0.3808]]], device='cuda:0')


In [12]:
# moving existing tensor to GPU
tn3 = torch.rand((2,3)) # creating tensor on CPU
print(tn3)
print("pos id: ", id(tn3))
print("-----------")
tn3 = tn3.to(device) # moving tensor on GPU
print(tn3)
print("pos id: ", id(tn3))

tensor([[0.8995, 0.2343, 0.6266],
        [0.1394, 0.4603, 0.2964]])
pos id:  137647684783936
-----------
tensor([[0.8995, 0.2343, 0.6266],
        [0.1394, 0.4603, 0.2964]], device='cuda:0')
pos id:  137647684949456


### Comparing the speed of operations on GPU VS operations on CPU

In [20]:
import time

size = 10000 # matrix size

# creating matrices on CPU
toc1 = torch.rand((size,size))
toc2 = torch.rand((size,size))

# operation time measurement
start = time.time()
toc_res = torch.matmul(toc1,toc2)
cpu_time = time.time() - start

# creating matrices on GPU
tog1 = torch.rand((size,size),device=device)
tog2 = torch.rand((size,size),device=device)

# operation time measurement
start = time.time()
tog_res = torch.matmul(tog1,tog2)
gpu_time = time.time() - start

print(f"cpu time: {cpu_time} sec \ngpu time: {gpu_time} sec")

cpu time: 15.280505895614624 sec 
gpu time: 0.0007274150848388672 sec


## Reshaping Tensors

In [6]:
z1 = torch.rand(4,4)
print(z1)

tensor([[0.5375, 0.5484, 0.7211, 0.4921],
        [0.4178, 0.5622, 0.1207, 0.4533],
        [0.2118, 0.6406, 0.4779, 0.6113],
        [0.0976, 0.0966, 0.3504, 0.3673]])


In [11]:
# reshape
print(z1.reshape(2,8))
print(z1.reshape(2,8).shape,"\n------")

# flatten
print(z1.reshape(16))
print(z1.reshape(16).shape)
print("============================================================")
print(z1.reshape(-1))
print(z1.reshape(-1).shape)
print("============================================================")
print(z1.flatten())
print(z1.flatten().shape)

tensor([[0.5375, 0.5484, 0.7211, 0.4921, 0.4178, 0.5622, 0.1207, 0.4533],
        [0.2118, 0.6406, 0.4779, 0.6113, 0.0976, 0.0966, 0.3504, 0.3673]])
torch.Size([2, 8]) 
------
tensor([0.5375, 0.5484, 0.7211, 0.4921, 0.4178, 0.5622, 0.1207, 0.4533, 0.2118,
        0.6406, 0.4779, 0.6113, 0.0976, 0.0966, 0.3504, 0.3673])
torch.Size([16])
tensor([0.5375, 0.5484, 0.7211, 0.4921, 0.4178, 0.5622, 0.1207, 0.4533, 0.2118,
        0.6406, 0.4779, 0.6113, 0.0976, 0.0966, 0.3504, 0.3673])
torch.Size([16])
tensor([0.5375, 0.5484, 0.7211, 0.4921, 0.4178, 0.5622, 0.1207, 0.4533, 0.2118,
        0.6406, 0.4779, 0.6113, 0.0976, 0.0966, 0.3504, 0.3673])
torch.Size([16])


In [17]:
z2 = torch.rand(2,3,4)
print(z2)
print(z2.shape)

tensor([[[0.4503, 0.9195, 0.8978, 0.2396],
         [0.7289, 0.9944, 0.9214, 0.0947],
         [0.2236, 0.6241, 0.2386, 0.3387]],

        [[0.0063, 0.6403, 0.6373, 0.5190],
         [0.1247, 0.9267, 0.4740, 0.5727],
         [0.3188, 0.6925, 0.9323, 0.1570]]])
torch.Size([2, 3, 4])


In [13]:
# permute
"""
rearrange the dimensions of a tensor.
It returns a new tensor with the same data as the original but with its
dimensions reordered according to the specified order.

usecase:
In image processing, tensors often have shapes like (C, H, W)
(Channel, Height, Width) or (N, C, H, W) (Batch, Channel, Height, Width).

Suppose you need to convert an image tensor from (C, H, W) to (H, W, C)
(as expected by some libraries like OpenCV).
"""

print(z2.permute(2,0,1))
print(z2.permute(2,0,1).shape)

tensor([[[0.4497, 0.9270, 0.4840],
         [0.2462, 0.0379, 0.0848]],

        [[0.3063, 0.1125, 0.8437],
         [0.4769, 0.8260, 0.9161]],

        [[0.2982, 0.0532, 0.0903],
         [0.2037, 0.7304, 0.4593]],

        [[0.1747, 0.8204, 0.7634],
         [0.2673, 0.9434, 0.0510]]])
torch.Size([4, 2, 3])


In [14]:
print(z2.permute(1,2,0))
print(z2.permute(1,2,0).shape)

tensor([[[0.4497, 0.2462],
         [0.3063, 0.4769],
         [0.2982, 0.2037],
         [0.1747, 0.2673]],

        [[0.9270, 0.0379],
         [0.1125, 0.8260],
         [0.0532, 0.7304],
         [0.8204, 0.9434]],

        [[0.4840, 0.0848],
         [0.8437, 0.9161],
         [0.0903, 0.4593],
         [0.7634, 0.0510]]])
torch.Size([3, 4, 2])


In [16]:
print(z2.permute(0,1,2)) # keeping tensor shape as it is
print(z2.permute(0,1,2).shape)

tensor([[[0.4497, 0.3063, 0.2982, 0.1747],
         [0.9270, 0.1125, 0.0532, 0.8204],
         [0.4840, 0.8437, 0.0903, 0.7634]],

        [[0.2462, 0.4769, 0.2037, 0.2673],
         [0.0379, 0.8260, 0.7304, 0.9434],
         [0.0848, 0.9161, 0.4593, 0.0510]]])
torch.Size([2, 3, 4])


In [5]:
# Create a tensor of shape (2, 3, 4)
x = torch.randn(2, 3, 4)
print("Original shape:", x.shape)
print("Original strides:", x.stride())

# Permute dimensions to (4, 3, 2)
y = x.permute(2, 1, 0)
print("Permuted shape:", y.shape)
print("Permuted strides:", y.stride())

Original shape: torch.Size([2, 3, 4])
Original strides: (12, 4, 1)
Permuted shape: torch.Size([4, 3, 2])
Permuted strides: (1, 4, 12)


In [9]:
# unsqueeze -> adding new dimension at specified position
z3 = torch.rand(2,4)
print(z3)
print(z3.shape)
print("=======================")
print(z3.unsqueeze(0))
print(z3.unsqueeze(0).shape)
print("=======================")
print(z3.unsqueeze(1))
print(z3.unsqueeze(1).shape)

tensor([[0.9361, 0.9800, 0.6825, 0.9446],
        [0.1461, 0.3444, 0.4662, 0.6509]])
torch.Size([2, 4])
tensor([[[0.9361, 0.9800, 0.6825, 0.9446],
         [0.1461, 0.3444, 0.4662, 0.6509]]])
torch.Size([1, 2, 4])
tensor([[[0.9361, 0.9800, 0.6825, 0.9446]],

        [[0.1461, 0.3444, 0.4662, 0.6509]]])
torch.Size([2, 1, 4])


In [10]:
z3 = torch.rand(3,2,4)
print(z3)
print(z3.shape)
print("=======================")
print(z3.unsqueeze(0))
print(z3.unsqueeze(0).shape)
print("=======================")
print(z3.unsqueeze(1))
print(z3.unsqueeze(1).shape)
print("=======================")
print(z3.unsqueeze(2))
print(z3.unsqueeze(2).shape)

tensor([[[0.4857, 0.6973, 0.8087, 0.0641],
         [0.0103, 0.3190, 0.9779, 0.9550]],

        [[0.5263, 0.4109, 0.2368, 0.3458],
         [0.9952, 0.6133, 0.2767, 0.6828]],

        [[0.2091, 0.9884, 0.9401, 0.2631],
         [0.4152, 0.7402, 0.8823, 0.4566]]])
torch.Size([3, 2, 4])
tensor([[[[0.4857, 0.6973, 0.8087, 0.0641],
          [0.0103, 0.3190, 0.9779, 0.9550]],

         [[0.5263, 0.4109, 0.2368, 0.3458],
          [0.9952, 0.6133, 0.2767, 0.6828]],

         [[0.2091, 0.9884, 0.9401, 0.2631],
          [0.4152, 0.7402, 0.8823, 0.4566]]]])
torch.Size([1, 3, 2, 4])
tensor([[[[0.4857, 0.6973, 0.8087, 0.0641],
          [0.0103, 0.3190, 0.9779, 0.9550]]],


        [[[0.5263, 0.4109, 0.2368, 0.3458],
          [0.9952, 0.6133, 0.2767, 0.6828]]],


        [[[0.2091, 0.9884, 0.9401, 0.2631],
          [0.4152, 0.7402, 0.8823, 0.4566]]]])
torch.Size([3, 1, 2, 4])
tensor([[[[0.4857, 0.6973, 0.8087, 0.0641]],

         [[0.0103, 0.3190, 0.9779, 0.9550]]],


        [[[0.5263, 0.410

In [12]:
# squeeze
"""
Removes all dimensions of size 1 from the tensor's shape. If a specific
dimension is specified with dim, it removes that dimension only if its size is 1.
"""
z4 = torch.rand(1,2,4)
print(z4)
print(z4.shape)
print("=======================")
print(z4.squeeze(0))
print(z4.squeeze(0).shape)
print("=======================")
print(z4.squeeze(1))
print(z4.squeeze(1).shape)
print("=======================")
print(z4.squeeze())
print(z4.squeeze().shape)

tensor([[[0.2030, 0.4615, 0.5432, 0.5483],
         [0.7444, 0.0255, 0.9939, 0.8570]]])
torch.Size([1, 2, 4])
tensor([[0.2030, 0.4615, 0.5432, 0.5483],
        [0.7444, 0.0255, 0.9939, 0.8570]])
torch.Size([2, 4])
tensor([[[0.2030, 0.4615, 0.5432, 0.5483],
         [0.7444, 0.0255, 0.9939, 0.8570]]])
torch.Size([1, 2, 4])
tensor([[0.2030, 0.4615, 0.5432, 0.5483],
        [0.7444, 0.0255, 0.9939, 0.8570]])
torch.Size([2, 4])


## Numpy and pytorch

In [14]:
# converting pytorch tensor into numpy array

z5 = torch.tensor([1,2,3]) # pytorch tensor
print(z5)
print(type(z5))
print("=============================================")
z6 = z5.numpy() # converting into numpy array
print(z6)
print(type(z6))

tensor([1, 2, 3])
<class 'torch.Tensor'>
[1 2 3]
<class 'numpy.ndarray'>


In [16]:
# converting numpy array into pytorch tensor
import numpy as np
z7 = np.array([10,12,23])
print(z7)
print(type(z7))
print("=============================================")
z8 = torch.from_numpy(z7) # converting into pytorch tensor
print(z8)
print(type(z8))

[10 12 23]
<class 'numpy.ndarray'>
tensor([10, 12, 23])
<class 'torch.Tensor'>
